placement:
  managedCluster:
    clusterName: setu-flagging-filtering
    config:
      gceClusterConfig:
        zoneUri: asia-south1-a
        
jobs:
- pysparkJob:
    fileUris:
    mainPythonFileUri: your_pyspark_script.py
    properties:
      spark.executorEnv.MY_VAR1: 'default_value'
      spark.executorEnv.MY_VAR2: 'default_value'
  stepId: FLAGGING_AND_FILTERING
- pysparkJob:
    fileUris:
    mainPythonFileUri: your_pyspark_script.py
    properties:
      spark.executorEnv.MY_VAR1: 'default_value'
      spark.executorEnv.MY_VAR2: 'default_value'
  stepId: DOCUMENT_REMOVAL
  prerequisiteStepIds:
  - FLAGGING_AND_FILTERING

parameters:
  - name: MY_VAR1
    fields:
      - jobs[STEP_NAME'].pysparkJob.properties['spark.executorEnv.MY_VAR1']
  - name: MY_VAR2
    fields:
      - jobs[STEP_NAME'].pysparkJob.properties['spark.executorEnv.MY_VAR2']